// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright (c) 2024, Renesas Electronics Corporation
 */

#include <util.h>
#include <tee_api_types.h>
#include <kernel/panic.h>

#include "pta_rsip_util.h"

static const struct rsip_key_desc key_descs[] = {
	[RSIP_KEY_TYPE_AES_128] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_AES_128, RSIP_BYTE_SIZE_ENCRYPTED_KEY_AES_128, },
	[RSIP_KEY_TYPE_AES_256] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_AES_256, RSIP_BYTE_SIZE_ENCRYPTED_KEY_AES_256, },
	[RSIP_KEY_TYPE_AES_128_XTS] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_AES_128_XTS, RSIP_BYTE_SIZE_ENCRYPTED_KEY_AES_128_XTS, },
	[RSIP_KEY_TYPE_AES_256_XTS] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_AES_256_XTS, RSIP_BYTE_SIZE_ENCRYPTED_KEY_AES_256_XTS, },
	[RSIP_KEY_TYPE_ECC_secp192r1_PUBLIC] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_ECC_secp192r1_PUBLIC, RSIP_BYTE_SIZE_ENCRYPTED_KEY_ECC_secp192r1_PUBLIC, },
	[RSIP_KEY_TYPE_ECC_secp192r1_PRIVATE] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_ECC_secp192r1_PRIVATE, RSIP_BYTE_SIZE_ENCRYPTED_KEY_ECC_secp192r1_PRIVATE, },
	[RSIP_KEY_TYPE_ECC_secp224r1_PUBLIC] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_ECC_secp224r1_PUBLIC, RSIP_BYTE_SIZE_ENCRYPTED_KEY_ECC_secp224r1_PUBLIC, },
	[RSIP_KEY_TYPE_ECC_secp224r1_PRIVATE] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_ECC_secp224r1_PRIVATE, RSIP_BYTE_SIZE_ENCRYPTED_KEY_ECC_secp224r1_PRIVATE, },
	[RSIP_KEY_TYPE_ECC_secp256r1_PUBLIC] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_ECC_secp256r1_PUBLIC, RSIP_BYTE_SIZE_ENCRYPTED_KEY_ECC_secp256r1_PUBLIC, },
	[RSIP_KEY_TYPE_ECC_secp256r1_PRIVATE] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_ECC_secp256r1_PRIVATE, RSIP_BYTE_SIZE_ENCRYPTED_KEY_ECC_secp256r1_PRIVATE, },
	[RSIP_KEY_TYPE_HMAC_SHA1] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_HMAC_SHA1, RSIP_BYTE_SIZE_ENCRYPTED_KEY_HMAC_SHA1, },
	[RSIP_KEY_TYPE_HMAC_SHA224] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_HMAC_SHA224, RSIP_BYTE_SIZE_ENCRYPTED_KEY_HMAC_SHA224, },
	[RSIP_KEY_TYPE_HMAC_SHA256] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_HMAC_SHA256, RSIP_BYTE_SIZE_ENCRYPTED_KEY_HMAC_SHA256, },
	[RSIP_KEY_TYPE_RSA_1024_PUBLIC_ENHANCED] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_RSA_1024_PUBLIC_ENHANCED, RSIP_BYTE_SIZE_ENCRYPTED_KEY_RSA_1024_PUBLIC_ENHANCED, },
	[RSIP_KEY_TYPE_RSA_1024_PRIVATE_ENHANCED] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_RSA_1024_PRIVATE_ENHANCED, RSIP_BYTE_SIZE_ENCRYPTED_KEY_RSA_1024_PRIVATE_ENHANCED, },
	[RSIP_KEY_TYPE_RSA_2048_PUBLIC_ENHANCED] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_RSA_2048_PUBLIC_ENHANCED, RSIP_BYTE_SIZE_ENCRYPTED_KEY_RSA_2048_PUBLIC_ENHANCED, },
	[RSIP_KEY_TYPE_RSA_2048_PRIVATE_ENHANCED] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_RSA_2048_PRIVATE_ENHANCED, RSIP_BYTE_SIZE_ENCRYPTED_KEY_RSA_2048_PRIVATE_ENHANCED, },
	[RSIP_KEY_TYPE_RSA_3072_PUBLIC] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_RSA_3072_PUBLIC, RSIP_BYTE_SIZE_ENCRYPTED_KEY_RSA_3072_PUBLIC, },
	[RSIP_KEY_TYPE_RSA_3072_PRIVATE] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_RSA_3072_PRIVATE, RSIP_BYTE_SIZE_ENCRYPTED_KEY_RSA_3072_PRIVATE, },
	[RSIP_KEY_TYPE_RSA_4096_PUBLIC] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_RSA_4096_PUBLIC, RSIP_BYTE_SIZE_ENCRYPTED_KEY_RSA_4096_PUBLIC, },
	[RSIP_KEY_TYPE_RSA_4096_PRIVATE] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_RSA_4096_PRIVATE, RSIP_BYTE_SIZE_ENCRYPTED_KEY_RSA_4096_PRIVATE, },
	[RSIP_KEY_TYPE_ECC_BRAINPOOLP256R1_PUBLIC] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_ECC_BRAINPOOLP256R1_PUBLIC, RSIP_BYTE_SIZE_ENCRYPTED_KEY_ECC_BRAINPOOLP256R1_PUBLIC, },
	[RSIP_KEY_TYPE_ECC_BRAINPOOLP256R1_PRIVATE] = {
		RSIP_BYTE_SIZE_WRAPPED_KEY_ECC_BRAINPOOLP256R1_PRIVATE, RSIP_BYTE_SIZE_ENCRYPTED_KEY_ECC_BRAINPOOLP256R1_PRIVATE, },
};

TEE_Result get_key_desc(rsip_key_type_t type,
			const struct rsip_key_desc **key_desc)
{
	if (type >= ARRAY_SIZE(key_descs))
		return TEE_ERROR_BAD_PARAMETERS;
	if (0 == key_descs[type].wrapped_size)
		return TEE_ERROR_BAD_PARAMETERS;
	if (0 == key_descs[type].encrypted_size)
		return TEE_ERROR_BAD_PARAMETERS;

	*key_desc = &key_descs[type];
	return TEE_SUCCESS;
}

TEE_Result get_keypair_desc(rsip_key_pair_type_t type,
			    const struct rsip_key_desc **prikey_desc,
			    const struct rsip_key_desc **pubkey_desc)
{
	TEE_Result res = TEE_ERROR_GENERIC;

	rsip_key_type_t prikey = 0;
	rsip_key_type_t pubkey = 0;

	switch (type) {
	case RSIP_KEY_PAIR_TYPE_ECC_secp192r1:
		prikey = RSIP_KEY_TYPE_ECC_secp192r1_PRIVATE;
		pubkey = RSIP_KEY_TYPE_ECC_secp192r1_PUBLIC;
		break;
	case RSIP_KEY_PAIR_TYPE_ECC_secp224r1:
		prikey = RSIP_KEY_TYPE_ECC_secp224r1_PRIVATE;
		pubkey = RSIP_KEY_TYPE_ECC_secp224r1_PUBLIC;
		break;
	case RSIP_KEY_PAIR_TYPE_ECC_secp256r1:
		prikey = RSIP_KEY_TYPE_ECC_secp256r1_PRIVATE;
		pubkey = RSIP_KEY_TYPE_ECC_secp256r1_PUBLIC;
		break;
	case RSIP_KEY_PAIR_TYPE_ECC_BRAINPOOLP256R1:
		prikey = RSIP_KEY_TYPE_ECC_BRAINPOOLP256R1_PRIVATE;
		pubkey = RSIP_KEY_TYPE_ECC_BRAINPOOLP256R1_PUBLIC;
		break;
	case RSIP_KEY_PAIR_TYPE_RSA_1024:
		prikey = RSIP_KEY_TYPE_RSA_1024_PRIVATE_ENHANCED;
		pubkey = RSIP_KEY_TYPE_RSA_1024_PUBLIC_ENHANCED;
		break;
	case RSIP_KEY_PAIR_TYPE_RSA_2048:
		prikey = RSIP_KEY_TYPE_RSA_2048_PRIVATE_ENHANCED;
		pubkey = RSIP_KEY_TYPE_RSA_2048_PUBLIC_ENHANCED;
		break;
	case RSIP_KEY_PAIR_TYPE_RSA_3072:
		prikey = RSIP_KEY_TYPE_RSA_3072_PRIVATE;
		pubkey = RSIP_KEY_TYPE_RSA_3072_PUBLIC;
		break;
	case RSIP_KEY_PAIR_TYPE_RSA_4096:
		prikey = RSIP_KEY_TYPE_RSA_4096_PRIVATE;
		pubkey = RSIP_KEY_TYPE_RSA_4096_PUBLIC;
		break;
	default:
		return TEE_ERROR_BAD_PARAMETERS;
	}

	res = get_key_desc(prikey, prikey_desc);
	if (res != TEE_SUCCESS)
		return res;
	res = get_key_desc(pubkey, pubkey_desc);
	if (res != TEE_SUCCESS)
		return res;

	return TEE_SUCCESS;
}

TEE_Result get_digest_size(rsip_hash_type_t hash_type, size_t *digest_size)
{
	switch (hash_type) {
	case RSIP_HASH_TYPE_SHA1:
		*digest_size = RSIP_DIGEST_SIZE_SHA1;
		return TEE_SUCCESS;
	case RSIP_HASH_TYPE_SHA224:
		*digest_size = RSIP_DIGEST_SIZE_SHA224;
		return TEE_SUCCESS;
	case RSIP_HASH_TYPE_SHA256:
		*digest_size = RSIP_DIGEST_SIZE_SHA256;
		return TEE_SUCCESS;
	case RSIP_HASH_TYPE_SHA384:
		*digest_size = RSIP_DIGEST_SIZE_SHA384;
		return TEE_SUCCESS;
	case RSIP_HASH_TYPE_SHA512:
		*digest_size = RSIP_DIGEST_SIZE_SHA512;
		return TEE_SUCCESS;
	case RSIP_HASH_TYPE_SHA512_224:
		*digest_size = RSIP_DIGEST_SIZE_SHA224;
		return TEE_SUCCESS;
	case RSIP_HASH_TYPE_SHA512_256:
		*digest_size = RSIP_DIGEST_SIZE_SHA256;
		return TEE_SUCCESS;
	default:
		return TEE_ERROR_BAD_PARAMETERS;
	}
}

/*
 * Convert RSIP/FSP error codes to TEE_Result.
 */
TEE_Result rsip_err_to_tee(fsp_err_t err)
{
	switch ((uint32_t)err) {
	case FSP_SUCCESS:
		return TEE_SUCCESS;
	case FSP_ERR_ASSERTION:
	case FSP_ERR_CRYPTO_RSIP_FATAL:
		return TEE_ERROR_GENERIC;
	case FSP_ERR_INVALID_ARGUMENT:
	case FSP_ERR_INVALID_SIZE:
	case FSP_ERR_CRYPTO_RSIP_KEY_SET_FAIL:
		return TEE_ERROR_BAD_PARAMETERS;
	case FSP_ERR_UNSUPPORTED:
	case FSP_ERR_NOT_ENABLED:
		return TEE_ERROR_NOT_SUPPORTED;
	case FSP_ERR_NOT_OPEN:
	case FSP_ERR_INVALID_STATE:
		return TEE_ERROR_BAD_STATE;
	case FSP_ERR_ALREADY_OPEN:
		return TEE_ERROR_ACCESS_CONFLICT;
	case FSP_ERR_CRYPTO_RSIP_RESOURCE_CONFLICT:
		return TEE_ERROR_BUSY;
	case FSP_ERR_CRYPTO_RSIP_AUTHENTICATION:
		return TEE_ERROR_MAC_INVALID;
	default:
		EMSG("Unhandled RSIP error: %#" PRIx32, (uint32_t)err);
		return TEE_ERROR_GENERIC;
	}
}

TEE_Result rsip_verify_err_to_tee(fsp_err_t err, enum rsip_verify_type type)
{
	if (err != FSP_ERR_CRYPTO_RSIP_FAIL)
		return rsip_err_to_tee(err);

	switch (type) {
	case RSIP_VERIFY_ECC:
	case RSIP_VERIFY_RSA:
		return TEE_ERROR_SIGNATURE_INVALID;
	case RSIP_VERIFY_MAC:
		return TEE_ERROR_MAC_INVALID;
	default:
		panic();
	}
}
