/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (c) 2023-2025, Renesas Electronics Corporation
 */

#ifndef __SYS_REGS_H__
#define __SYS_REGS_H__

#include <util.h>

#define SYS_PRCRN_OFFSET UL(0x4200)
#define SYS_PRCRS_OFFSET UL(0x6000)

#define SYS_PRCR_CGC BIT(0)
#define SYS_PRCR_PWR BIT(1)
#define SYS_PRCR_GPIO BIT(2)
#define SYS_PRCR_SYSCTRL BIT(3)

#define SYS_PRCR_MASK \
	UL(SYS_PRCR_CGC | SYS_PRCR_PWR | SYS_PRCR_GPIO | SYS_PRCR_SYSCTRL)
#define SYS_PRCR_KEY_CODE UL(0xA500)

#define SYS_SSTPCR0_OFFSET UL(0x1200)
#define SYS_SSTPCR1_OFFSET UL(0x1204)
#define SYS_SSTPCR4_OFFSET UL(0x0200)
#define SYS_SSTPCR5_OFFSET UL(0x0204)
#define SYS_SSTPCR6_OFFSET UL(0x0208)
#define SYS_SSTPCR7_OFFSET UL(0x020C)

#define SYS_SSTPCR6_XSPI0_REQ BIT(0)
#define SYS_SSTPCR6_XSPI0_ACK BIT(1)
#define SYS_SSTPCR6_XSPI1_REQ BIT(4)
#define SYS_SSTPCR6_XSPI1_ACK BIT(5)

#define SYS_CS0ENDAD_XSPI0_OFFSET UL(0x3004)
#define SYS_CS0ENDAD_XSPI1_OFFSET UL(0x3104)

#endif /* __SYS_REGS_H__ */
