/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Copyright (c) 2024, Renesas Electronics Corporation
 */

#ifndef R_RSIP_CFG_H_
#define R_RSIP_CFG_H_

#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_ECC_192_QX                    (24U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_ECC_192_QY                    (56U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_ECC_224_QX                    (20U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_ECC_224_QY                    (52U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_ECC_256_QX                    (16U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_ECC_256_QY                    (48U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_RSA_1024_N                    (16U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_RSA_1024_E                    (144U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_RSA_2048_N                    (16U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_RSA_2048_E                    (272U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_RSA_3072_N                    (16U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_RSA_3072_E                    (400U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_RSA_4096_N                    (16U)
#define RSIP_CFG_BYTE_POS_WRAPPED_PUBLIC_KEY_RSA_4096_E                    (528U)

#ifndef RSIP_CFG_PARAM_CHECKING_ENABLE
#define RSIP_CFG_PARAM_CHECKING_ENABLE                                     (1)
#endif
#ifndef RSIP_CFG_KEY_GENERATE_AES_128_ENABLE
#define RSIP_CFG_KEY_GENERATE_AES_128_ENABLE                               (1)
#endif
#ifndef RSIP_CFG_KEY_GENERATE_AES_256_ENABLE
#define RSIP_CFG_KEY_GENERATE_AES_256_ENABLE                               (1)
#endif
#ifndef RSIP_CFG_KEY_GENERATE_AES_128_XTS_ENABLE
#define RSIP_CFG_KEY_GENERATE_AES_128_XTS_ENABLE                           (1)
#endif
#ifndef RSIP_CFG_KEY_GENERATE_AES_256_XTS_ENABLE
#define RSIP_CFG_KEY_GENERATE_AES_256_XTS_ENABLE                           (1)
#endif
#ifndef RSIP_CFG_KEY_PAIR_GENERATE_ECC_secp192r1_ENABLE
#define RSIP_CFG_KEY_PAIR_GENERATE_ECC_secp192r1_ENABLE                    (1)
#endif
#ifndef RSIP_CFG_KEY_PAIR_GENERATE_ECC_secp224r1_ENABLE
#define RSIP_CFG_KEY_PAIR_GENERATE_ECC_secp224r1_ENABLE                    (1)
#endif
#ifndef RSIP_CFG_KEY_PAIR_GENERATE_ECC_secp256r1_ENABLE
#define RSIP_CFG_KEY_PAIR_GENERATE_ECC_secp256r1_ENABLE                    (1)
#endif
#ifndef RSIP_CFG_KEY_PAIR_GENERATE_ECC_BRAINPOOLP256R1_ENABLE
#define RSIP_CFG_KEY_PAIR_GENERATE_ECC_BRAINPOOLP256R1_ENABLE              (1)
#endif
#ifndef RSIP_CFG_KEY_PAIR_GENERATE_RSA_1024_ENABLE
#define RSIP_CFG_KEY_PAIR_GENERATE_RSA_1024_ENABLE                         (1)
#endif
#ifndef RSIP_CFG_KEY_PAIR_GENERATE_RSA_2048_ENABLE
#define RSIP_CFG_KEY_PAIR_GENERATE_RSA_2048_ENABLE                         (1)
#endif
#ifndef RSIP_CFG_KEY_PAIR_GENERATE_RSA_3072_ENABLE
#define RSIP_CFG_KEY_PAIR_GENERATE_RSA_3072_ENABLE                         (1)
#endif
#ifndef RSIP_CFG_KEY_PAIR_GENERATE_RSA_4096_ENABLE
#define RSIP_CFG_KEY_PAIR_GENERATE_RSA_4096_ENABLE                         (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_AES_128_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_AES_128_ENABLE                       (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_AES_256_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_AES_256_ENABLE                       (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_AES_128_XTS_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_AES_128_XTS_ENABLE                   (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_AES_256_XTS_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_AES_256_XTS_ENABLE                   (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_secp192r1_PRIVATE_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_secp192r1_PRIVATE_ENABLE         (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_secp192r1_PUBLIC_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_secp192r1_PUBLIC_ENABLE          (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_secp224r1_PRIVATE_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_secp224r1_PRIVATE_ENABLE         (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_secp224r1_PUBLIC_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_secp224r1_PUBLIC_ENABLE          (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_secp256r1_PUBLIC_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_secp256r1_PUBLIC_ENABLE          (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_secp256r1_PRIVATE_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_secp256r1_PRIVATE_ENABLE         (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_BRAINPOOLP256R1_PUBLIC_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_BRAINPOOLP256R1_PUBLIC_ENABLE    (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_BRAINPOOLP256R1_PRIVATE_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_ECC_BRAINPOOLP256R1_PRIVATE_ENABLE   (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_1024_PUBLIC_ENHANCED_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_1024_PUBLIC_ENHANCED_ENABLE      (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_1024_PRIVATE_ENHANCED_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_1024_PRIVATE_ENHANCED_ENABLE     (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_2048_PUBLIC_ENHANCED_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_2048_PUBLIC_ENHANCED_ENABLE      (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_2048_PRIVATE_ENHANCED_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_2048_PRIVATE_ENHANCED_ENABLE     (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_3072_PUBLIC_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_3072_PUBLIC_ENABLE               (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_3072_PRIVATE_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_3072_PRIVATE_ENABLE              (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_4096_PUBLIC_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_4096_PUBLIC_ENABLE               (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_4096_PRIVATE_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_RSA_4096_PRIVATE_ENABLE              (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_HMAC_SHA_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_HMAC_SHA_ENABLE                      (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_KUK_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_KUK_ENABLE                           (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_UFPK_SECURE_BOOT_DECRYPTION_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_UFPK_SECURE_BOOT_DECRYPTION_ENABLE        (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_AES_128_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_AES_128_ENABLE                        (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_AES_256_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_AES_256_ENABLE                        (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_AES_128_XTS_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_AES_128_XTS_ENABLE                    (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_AES_256_XTS_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_AES_256_XTS_ENABLE                    (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_secp192r1_PUBLIC_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_secp192r1_PUBLIC_ENABLE           (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_secp192r1_PRIVATE_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_secp192r1_PRIVATE_ENABLE          (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_secp224r1_PUBLIC_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_secp224r1_PUBLIC_ENABLE           (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_secp224r1_PRIVATE_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_secp224r1_PRIVATE_ENABLE          (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_secp256r1_PUBLIC_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_secp256r1_PUBLIC_ENABLE           (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_secp256r1_PRIVATE_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_secp256r1_PRIVATE_ENABLE          (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_BRAINPOOLP256R1_PUBLIC_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_BRAINPOOLP256R1_PUBLIC_ENABLE     (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_BRAINPOOLP256R1_PRIVATE_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_ECC_BRAINPOOLP256R1_PRIVATE_ENABLE    (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_1024_PUBLIC_ENHANCED_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_1024_PUBLIC_ENHANCED_ENABLE       (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_1024_PRIVATE_ENHANCED_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_1024_PRIVATE_ENHANCED_ENABLE      (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_2048_PUBLIC_ENHANCED_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_2048_PUBLIC_ENHANCED_ENABLE       (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_2048_PRIVATE_ENHANCED_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_2048_PRIVATE_ENHANCED_ENABLE      (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_3072_PUBLIC_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_3072_PUBLIC_ENABLE                (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_3072_PRIVATE_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_3072_PRIVATE_ENABLE               (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_4096_PUBLIC_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_4096_PUBLIC_ENABLE                (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_4096_PRIVATE_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_RSA_4096_PRIVATE_ENABLE               (1)
#endif
#ifndef RSIP_CFG_KEY_IMPORT_WITH_KUK_HMAC_SHA_ENABLE
#define RSIP_CFG_KEY_IMPORT_WITH_KUK_HMAC_SHA_ENABLE                       (1)
#endif
#ifndef RSIP_CFG_AES_128_ECB_CBC_CTR_ENABLE
#define RSIP_CFG_AES_128_ECB_CBC_CTR_ENABLE                                (1)
#endif
#ifndef RSIP_CFG_AES_256_ECB_CBC_CTR_ENABLE
#define RSIP_CFG_AES_256_ECB_CBC_CTR_ENABLE                                (1)
#endif
#ifndef RSIP_CFG_AES_128_XTS_ENCRYPT_ENABLE
#define RSIP_CFG_AES_128_XTS_ENCRYPT_ENABLE                                (1)
#endif
#ifndef RSIP_CFG_AES_128_XTS_DECRYPT_ENABLE
#define RSIP_CFG_AES_128_XTS_DECRYPT_ENABLE                                (1)
#endif
#ifndef RSIP_CFG_AES_256_XTS_ENCRYPT_ENABLE
#define RSIP_CFG_AES_256_XTS_ENCRYPT_ENABLE                                (1)
#endif
#ifndef RSIP_CFG_AES_256_XTS_DECRYPT_ENABLE
#define RSIP_CFG_AES_256_XTS_DECRYPT_ENABLE                                (1)
#endif
#ifndef RSIP_CFG_AES_128_GCM_ENCRYPT_ENABLE
#define RSIP_CFG_AES_128_GCM_ENCRYPT_ENABLE                                (1)
#endif
#ifndef RSIP_CFG_AES_128_GCM_DECRYPT_ENABLE
#define RSIP_CFG_AES_128_GCM_DECRYPT_ENABLE                                (1)
#endif
#ifndef RSIP_CFG_AES_256_GCM_ENCRYPT_ENABLE
#define RSIP_CFG_AES_256_GCM_ENCRYPT_ENABLE                                (1)
#endif
#ifndef RSIP_CFG_AES_256_GCM_DECRYPT_ENABLE
#define RSIP_CFG_AES_256_GCM_DECRYPT_ENABLE                                (1)
#endif
#ifndef RSIP_CFG_AES_128_CMAC_ENABLE
#define RSIP_CFG_AES_128_CMAC_ENABLE                                       (1)
#endif
#ifndef RSIP_CFG_AES_256_CMAC_ENABLE
#define RSIP_CFG_AES_256_CMAC_ENABLE                                       (1)
#endif
#ifndef RSIP_CFG_RSA_1024_ENCRYPT_ENHANCED_ENABLE
#define RSIP_CFG_RSA_1024_ENCRYPT_ENHANCED_ENABLE                          (1)
#endif
#ifndef RSIP_CFG_RSA_1024_DECRYPT_ENHANCED_ENABLE
#define RSIP_CFG_RSA_1024_DECRYPT_ENHANCED_ENABLE                          (1)
#endif
#ifndef RSIP_CFG_RSA_2048_ENCRYPT_ENHANCED_ENABLE
#define RSIP_CFG_RSA_2048_ENCRYPT_ENHANCED_ENABLE                          (1)
#endif
#ifndef RSIP_CFG_RSA_2048_DECRYPT_ENHANCED_ENABLE
#define RSIP_CFG_RSA_2048_DECRYPT_ENHANCED_ENABLE                          (1)
#endif
#ifndef RSIP_CFG_RSA_3072_ENCRYPT_ENABLE
#define RSIP_CFG_RSA_3072_ENCRYPT_ENABLE                                   (1)
#endif
#ifndef RSIP_CFG_RSA_3072_DECRYPT_ENABLE
#define RSIP_CFG_RSA_3072_DECRYPT_ENABLE                                   (1)
#endif
#ifndef RSIP_CFG_RSA_4096_ENCRYPT_ENABLE
#define RSIP_CFG_RSA_4096_ENCRYPT_ENABLE                                   (1)
#endif
#ifndef RSIP_CFG_RSA_4096_DECRYPT_ENABLE
#define RSIP_CFG_RSA_4096_DECRYPT_ENABLE                                   (1)
#endif
#ifndef RSIP_CFG_HMAC_SHA1_ENABLE
#define RSIP_CFG_HMAC_SHA1_ENABLE                                          (1)
#endif
#ifndef RSIP_CFG_HMAC_SHA224_ENABLE
#define RSIP_CFG_HMAC_SHA224_ENABLE                                        (1)
#endif
#ifndef RSIP_CFG_HMAC_SHA256_ENABLE
#define RSIP_CFG_HMAC_SHA256_ENABLE                                        (1)
#endif


#endif /* R_RSIP_CFG_H_ */
